---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satisfactory-config
  namespace: satisfactory
data:
  MAXPLAYERS: "4" # (Default=4)
  DISABLE_SEASONAL_EVENTS: "0" # (Default=0)
  SEND_GAMEPLAY_DATA: "0" # (Default=1)
  SEND_CRASH_REPORTS: "False" # (Default=True)
  SERVER_TICK_RATE: "30" # (Default=30)
  AUTOSAVE_INTERVAL: "300" # Seconds (Default=300))
  NUM_ROTATING_AUTOSAVES: "3" # (Default=3)
  SERVER_RESTART_TIMESLOT: "780.000000" # Minutes from 12:00am UTC (Default=1440.000000)

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satisfactory-scripts
  namespace: satisfactory
data:
  init.sh: |
    #!/bin/bash
    set -ex
    if steamcmd +force_install_dir /home/ubuntu/SatisfactoryDedicatedServer \
    +login anonymous +app_update 1690800 validate +quit; then
      chown -R 1000:1000 /home/ubuntu/SatisfactoryDedicatedServer
      exit 0
    else
      rm -rf /home/ubuntu/SatisfactoryDedicatedServer
      exit 1
    fi

  start.sh: |
    #!/bin/bash
    set -ex
    /home/ubuntu/SatisfactoryDedicatedServer/FactoryServer.sh \
        -ini:Game:[/Script/Engine.GameSession]:MaxPlayers=$MAXPLAYERS \
        "-ini:GameUserSettings:[/Script/FactoryGame.FGGameUserSettings]:mIntValues=((\"FG.DisableSeasonalEvents\", $DISABLE_SEASONAL_EVENTS),(\"FG.SendGameplayData\", $SEND_GAMEPLAY_DATA))" \
        "-ini:GameUserSettings:[/Script/FactoryGame.FGGameUserSettings]:mFloatValues=((\"FG.ServerRestartTimeSlot\", $SERVER_RESTART_TIMESLOT))" \
        -ini:Engine:[CrashReportClient]:bImplicitSend=$SEND_CRASH_REPORTS \
        -ini:Engine:[/Script/OnlineSubsystemUtils.IpNetDriver]:NetServerMaxTickRate=$SERVER_TICK_RATE \
        -ini:Engine:[/Script/OnlineSubsystemUtils.IpNetDriver]:LanServerMaxTickRate=$SERVER_TICK_RATE \
        -ini:Engine:[/Script/SocketSubsystemEpic.EpicNetDriver]:NetServerMaxTickRate=$SERVER_TICK_RATE \
        -ini:Engine:[/Script/SocketSubsystemEpic.EpicNetDriver]:LanServerMaxTickRate=$SERVER_TICK_RATE \
        -ini:Engine:[/Script/Engine.Engine]:NetClientTicksPerSecond=$SERVER_TICK_RATE \
        -ini:GameUserSettings:[/Script/FactoryGame.FGGameUserSettings]:AutosaveInterval=$AUTOSAVE_INTERVAL \
        -ini:Engine:[/Script/FactoryGame.FGSaveSession]:mNumRotatingAutosaves=$NUM_ROTATING_AUTOSAVES \
        -ini:GameUserSettings:[/Script/FactoryGame.FGGameUserSettings]:ServerRestartTimeSlot=$SERVER_RESTART_TIMESLOT
