---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory-svc
  namespace: satisfactory
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201
  selector:
    app: satisfactory
  externalTrafficPolicy: Local
  ports:
  - name: 7777-udp
    port: 7777
    protocol: UDP
    targetPort: 7777
  - name: 7777-tcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888