---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: satisfactory
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-gamefiles-pv
  namespace: satisfactory
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/persistent_volumes/satisfactory/SatisfactoryDedicatedServer"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-configs-pv
  namespace: satisfactory
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/persistent_volumes/satisfactory/configs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-gamefiles-pvc
  namespace: satisfactory
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-configs-pvc
  namespace: satisfactory
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi