---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  namespace: satisfactory
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-gamefiles-pv
  namespace: satisfactory
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4.1
    - _netdev
  nfs:
    path: /volume1/kubernetes_volumes/satisfactory/SatisfactoryDedicatedServer
    server: 192.168.0.110
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-gamefiles-pvc
  namespace: satisfactory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-configs-pv
  namespace: satisfactory
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4.1
    - _netdev
  nfs:
    path: /volume1/kubernetes_volumes/satisfactory/configs
    server: 192.168.0.110
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-configs-pvc
  namespace: satisfactory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi